CREATE TABLE users(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name VARCHAR(200) NOT NULL,
  last_name VARCHAR(200) NUT NULL,
  email VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  role VARCHAR(20) NOT NULL,
  dob DATE,
  gender VARCHAR(20),
  address VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)